[package]
name = "irc-proto"
version = "0.0.0"
description = "The IRC protocol distilled."
authors = ["Aaron Weiss <awe@pdgn.co>"]
license = "MPL-2.0"
keywords = ["irc", "protocol", "tokio"]
categories = ["network-programming"]
documentation = "https://docs.rs/irc-proto/"
repository = "https://github.com/aatxe/irc"

[badges]
travis-ci = { repository = "aatxe/irc" }

[features]
default = ["tokio"]
tokio = ["tokio-codec", "tokio-io", "bytes"]

[dependencies]
bytes = { version = "0.4", optional = true }
encoding = "0.2"
failure = "0.1"
tokio-codec = { version = "0.2.0-alpha.5", optional = true }
tokio-io = { version = "0.2.0-alpha.5", optional = true }
