[package]
name = "irc-proto"
version = "0.0.0"
description = "The IRC protocol distilled."
authors = ["Aaron Weiss <awe@pdgn.co>"]
license = "MPL-2.0"
keywords = ["irc", "protocol", "tokio"]
categories = ["network-programming"]
documentation = "https://docs.rs/irc-proto/"
repository = "https://github.com/aatxe/irc"
edition = "2018"

[badges]
travis-ci = { repository = "aatxe/irc" }

[features]
default = ["tokio", "tokio-util", "bytes"]

[dependencies]
bytes = { version = "0.5", optional = true }
encoding = "0.2"
thiserror = "1.0.2"
tokio-util = { version = "0.2.0", optional = true }
tokio = { version = "0.2.6", optional = true }