language: rust
rust: nightly
sudo: false
script:
  - cargo test --all --features "toml yaml json"
  - cargo build
  - rustdoc --test README.md --extern irc=target/debug/libirc.rlib -L target/debug/deps
  - cargo run --bin build-bot
notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.pdgn.co:6697/#commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
