[package]
name = "irc"
version = "0.13.6"
description = "the irc crate – usable, async IRC for Rust "
authors = ["Aaron Weiss <awe@pdgn.co>"]
license = "MPL-2.0"
keywords = ["irc", "client", "thread-safe", "async", "tokio"]
categories = ["asynchronous", "network-programming"]
documentation = "https://docs.rs/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "aatxe/irc" }
is-it-maintained-issue-resolution = { repository = "aatxe/irc" }
is-it-maintained-open-issues = { repository = "aatxe/irc" }

[workspace]
members = [ "./", "irc-proto" ]

[features]
default = ["ctcp", "toml"]
ctcp = []
nochanlists = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
thiserror = "1.0.2"
bufstream = "0.1"
bytes = "0.4"
chrono = "0.4"
encoding = "0.2"
irc-proto = { version = "*", path = "irc-proto" }
log = "0.4"
native-tls = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
tokio = { version = "0.2.6", features = ["time", "net", "stream", "macros", "stream", "sync"] }
tokio-util = { version = "0.2.0", features = ["codec"] }
tokio-tls = "0.3.0"
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.7", optional = true }
toml = { version = "0.4", optional = true }
pin-utils = "0.1.0-alpha.4"
futures-channel = "0.3.1"
futures-util = { version = "0.3.1", features = ["sink"] }

[dev-dependencies]
futures = "0.3.1"
anyhow = "1.0.13"
args = "2.0"
getopts = "0.2"
env_logger = "0.6.2"

[patch.crates-io]
tokio = { git = "https://github.com/tokio-rs/tokio" }